[package]
name = "tf2tts-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tf2tts-core = { path = "../tf2tts-core" }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"
dotenvy = "0.15"